### ISSUE TITLE
Reformat the project into project-awesome format

### ISSUE THREAD

**Issue by alenrajsp** [firefly-cpp/awesome-computational-intelligence-in-sports#18]
I am trying to reformat the project into project-awesome format so it can be featured in https://github.com/sindresorhus/awesome repo.
Please add the following.

  ✖    1:1    The repository should have "awesome" as a GitHub topic               remark-lint:awesome-github
  ✖    1:1    The repository should have "awesome-list" as a GitHub topic          remark-lint:awesome-github

**Comment by firefly-cpp** [comment]
@alenrajsp, check it out.

**Comment by alenrajsp** [comment]
Thank you :) . I will try to conform to all the other requirements of the _awesome list_ repo and then submit the list to the central awesome list repository.
